project_id = "tqswuibgnkdvrfocwjou"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327

[auth]
enabled = true
port = 54329

[edge_functions]
enabled = true
port = 54328

[functions.create-custom-order]
verify_jwt = false

[functions.send-newsletter]
verify_jwt = false

[functions.verify-age-with-ai]
verify_jwt = false

[functions.chat-ai-support]
verify_jwt = false

[functions.send-contest-confirmation]
verify_jwt = false

[functions.stripe-checkout]
verify_jwt = false

[functions.send-bank-transfer-email]
verify_jwt = false

[functions.ai-product-recommendations]
verify_jwt = false

[functions.perfume-matcher-ai]
verify_jwt = false